/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"
#include "switch.h"
#include "lcd.h"


int c = 0;
extern volatile int count_flag;
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	char str[16]={" "};
	SystemInit();
	LcdInit();
	SwitchInit(SWITCH);
	DelayMs(1);
//	LedInit(LED_GREEN);
//	LedInit(LED_ORANGE);
//	LedInit(LED_RED);
//	LedInit(LED_BLUE);
//	while(1) {
//		LedBlink(LED_GREEN, 1000);
//		LedBlink(LED_ORANGE, 1000);
//		LedBlink(LED_RED, 1000);
//		LedBlink(LED_BLUE, 1000);
	while(1)
	{
		// clear display
		LcdWrite(LCD_CMD, LCD_CLEAR);
		LcdPuts(LCD_LINE1,"COUNT");

			if(count_flag == 1)
			{
			c++;
			sprintf(str,"%d",c);
			LcdPuts(LCD_LINE2,str);
			count_flag = 0;
			}
			DelayMs(500);
	}

	return 0;
}


